name: Release

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/http_service
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          flavor: |
            latest=false

          tags: |
            type=sha,format=long
            type=match,pattern=^${{ inputs.image-name }}-(v\d+\.\d+\.\d+.*)$,group=1
            type=match,pattern=^${{ inputs.image-name }}-(v\d+\.\d+\.\d+)-(dev).*$,group=2

          labels: |
            org.opencontainers.image.title=${{ inputs.image-name }}
            org.opencontainers.image.description=Docker image for ${{ inputs.image-name }} from ${{ github.repository_owner }}/${{ github.repository }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}


      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}
          build-args: |
            GIT_HASH=${{ github.sha }}
