name: Release

permissions:
  contents: write

on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_SHA=${{ env.COMMIT_SHA_FULL }}
            GIT_REPOSITORY_URL=${{ env.REPOSITORY_URL }}
